### ISSUE TITLE
Rename ORKTaskResult+MORK category header to match implementation

### ISSUE THREAD

**Issue by medidatakerry** [mdsol/MORK#12]
The header `ORKTaskResult+MORK.h` not having a like-named implementation file is quite confusing as it doesn't follow common naming expectations.  I see a commit message where it was blatantly done this way so as to only expose it to `ORKTaskResult` only but I'm not sure why?  Based on the implementation, both `ORKTaskResult` and `ORKStepResult` can use it.

I think this should be renamed `ORKCollectionResult+MORK.h` to match `ORKCollectionResult+MORK.m` to follow traditional objective-c naming patterns.

This also makes much more sense as both `ORKTaskResult` and `ORKStepResult` are subclasses of `ORKCollectionResult` and both can (and do) use the category extension.

**Comment by jtomson-mdsol** [comment]
Thanks Kerry this is a little odd agreed.

As an external interface we're only really interested in serializing `ORKTaskResult` instances, not individual `ORKStepResult` - even if we do operate on `ORKStepResult` internally. Do you have any ideas on how we could communicate this more clearly?

**Comment by medidatakerry** [comment]
Yeah, lemme marinate on this a little.  If we rename the both .h/.m of the category to `ORKTaskResult+MORK`, there's bound to be some way to have a class extension for `ORKStepResult` added to the .m file so we can use it for that guy as well, while also maintaining some semblance of clarity for others.

**Comment by medidatakerry** [comment]
Ok, this works to just use a private function in the implementation file to do all the heavy lifting.  The explosed `ORKTaskResult` method just calls into the function while `ORKStepResult` can call the function directly in the implementation file.
